#pragma once
//TODO ป๓ลย
#include "PlayerState_Idle.h"
#include "PlayerState_Walk.h"
#include "PlayerState_Run.h"
#include "PlayerState_Jump.h"

#include "PlayerState_DashLeft.h"
#include "PlayerState_DashRight.h"
#include "PlayerState_DashFront.h"
#include "PlayerState_DashBack.h"

#include "PlayerState_Attack1.h"
#include "PlayerState_Attack2.h"
#include "PlayerState_Attack3.h"
#include "PlayerState_Attack4.h"
#include "PlayerState_Attack5.h"
#include "PlayerState_Attack6.h"
#include "PlayerState_Attack7.h"
#include "PlayerState_Attack8.h"

#include "PlayerState_BlowAwayHit.h"
#include "PlayerState_MoreMoreWeakHit.h"
#include "PlayerState_MoreWeakHit.h"
#include "PlayerState_WeakHit.h"
#include "PlayerState_BreakFall.h"
#include "PlayerState_Sturn.h"
#include "PlayerState_Dead.h"
#include "PlayerState_UpperHit.h"
#include "PlayerState_DownHit.h"
#include "PlayerState_Depress.h"



#include "PlayerState_BloodyMode.h"
#include "PlayerState_BloodyMode_Idle.h"
#include "PlayerState_BloodyMode_Run.h"
#include "PlayerState_BloodyMode_Attack1.h"
#include "PlayerState_BloodyMode_Attack2.h"
#include "PlayerState_BloodyMode_Attack3.h"
#include "PlayerState_BloodyMode_Attack4.h"
#include "PlayerState_BloodyMode_Attack5.h"
#include "PlayerState_BloodyMode_Attack6.h"
#include "PlayerState_BloodyMode_Attack7.h"
#include "PlayerState_BloodyMode_Attack8.h"
